In [3]:
import tensorflow as tf
import numpy as np
import pandas as pd
import os 
import matplotlib.pyplot as plt

In [4]:
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.backend import one_hot

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
os.listdir('drive/My Drive/Projects/gene_exp_rna_seq')

['data.csv', 'labels.csv', 'labels.gsheet', 'Split1_60_40']

In [7]:
data = pd.read_csv('drive/My Drive/Projects/gene_exp_rna_seq/data.csv',delimiter=',')
labels = pd.read_csv('drive/My Drive/Projects/gene_exp_rna_seq/labels.csv',delimiter=',')

In [8]:
data.describe()

           gene_0      gene_1      gene_2  ...  gene_20528  gene_20529  gene_20530
count  801.000000  801.000000  801.000000  ...  801.000000  801.000000  801.000000
mean     0.026642    3.010909    3.095350  ...    9.590726    5.528177    0.095411
std      0.136850    1.200828    1.065601  ...    0.563849    2.073859    0.364529
min      0.000000    0.000000    0.000000  ...    7.864533    0.593975    0.000000
25%      0.000000    2.299039    2.390365  ...    9.244219    4.092385    0.000000
50%      0.000000    3.143687    3.127006  ...    9.566511    5.218618    0.000000
75%      0.000000    3.883484    3.802534  ...    9.917888    6.876382    0.000000
max      1.482332    6.237034    6.063484  ...   12.813320   11.205836    5.254133

[8 rows x 20531 columns]

In [18]:
data.head()

  Unnamed: 0  gene_0    gene_1  ...  gene_20528  gene_20529  gene_20530
0   sample_0     0.0  2.017209  ...    8.921326    5.286759         0.0
1   sample_1     0.0  0.592732  ...    9.397854    2.094168         0.0
2   sample_2     0.0  3.511759  ...   10.090470    1.683023         0.0
3   sample_3     0.0  3.663618  ...    9.684365    3.292001         0.0
4   sample_4     0.0  2.655741  ...    9.461191    5.110372         0.0

[5 rows x 20532 columns]

In [10]:
labels.head()

  Unnamed: 0 Class
0   sample_0  PRAD
1   sample_1  LUAD
2   sample_2  PRAD
3   sample_3  PRAD
4   sample_4  BRCA

In [11]:
data.isnull()

     Unnamed: 0  gene_0  gene_1  ...  gene_20528  gene_20529  gene_20530
0         False   False   False  ...       False       False       False
1         False   False   False  ...       False       False       False
2         False   False   False  ...       False       False       False
3         False   False   False  ...       False       False       False
4         False   False   False  ...       False       False       False
..          ...     ...     ...  ...         ...         ...         ...
796       False   False   False  ...       False       False       False
797       False   False   False  ...       False       False       False
798       False   False   False  ...       False       False       False
799       False   False   False  ...       False       False       False
800       False   False   False  ...       False       False       False

[801 rows x 20532 columns]

In [12]:
data['Unnamed: 0']

0        sample_0
1        sample_1
2        sample_2
3        sample_3
4        sample_4
          ...
796    sample_796
797    sample_797
798    sample_798
799    sample_799
800    sample_800
Name: Unnamed: 0, Length: 801, dtype: object

In [13]:
#split into Train Validation and Test Samples ....... How do you wanna do it ... using a prebuilt function or mannually  ..? your choice .. 
#so lets look up for some function which randomly samples so its easy for everyone 
# We Need to  join both  the labels and the data file cause it would be stupid if we just split the train data seperately from the labels of train data .
# so lets join first and then use the sklearn fucntion of splitting

In [27]:
df = pd.DataFrame(data)

In [31]:
df.join(labels.set_index('Unnamed: 0'), on='Unnamed: 0')

In [32]:
df1.head()#;labels.head()

   gene_0    gene_1    gene_2  ...  gene_20529  gene_20530  Class
0     0.0  2.017209  3.265527  ...    5.286759         0.0   PRAD
1     0.0  0.592732  1.588421  ...    2.094168         0.0   LUAD
2     0.0  3.511759  4.327199  ...    1.683023         0.0   PRAD
3     0.0  3.663618  4.507649  ...    3.292001         0.0   PRAD
4     0.0  2.655741  2.821547  ...    5.110372         0.0   BRCA

[5 rows x 20532 columns]

In [17]:
#df.join(labels.set_index('Unnamed: 0'), on='Unnamed: 0')
df.merge(labels, left_on='Unnamed: 0', right_on='Class')

Empty DataFrame
Columns: [Unnamed: 0_x, gene_0, gene_1, gene_2, gene_3, gene_4, gene_5, gene_6, gene_7, gene_8, gene_9, gene_10, gene_11, gene_12, gene_13, gene_14, gene_15, gene_16, gene_17, gene_18, gene_19, gene_20, gene_21, gene_22, gene_23, gene_24, gene_25, gene_26, gene_27, gene_28, gene_29, gene_30, gene_31, gene_32, gene_33, gene_34, gene_35, gene_36, gene_37, gene_38, gene_39, gene_40, gene_41, gene_42, gene_43, gene_44, gene_45, gene_46, gene_47, gene_48, gene_49, gene_50, gene_51, gene_52, gene_53, gene_54, gene_55, gene_56, gene_57, gene_58, gene_59, gene_60, gene_61, gene_62, gene_63, gene_64, gene_65, gene_66, gene_67, gene_68, gene_69, gene_70, gene_71, gene_72, gene_73, gene_74, gene_75, gene_76, gene_77, gene_78, gene_79, gene_80, gene_81, gene_82, gene_83, gene_84, gene_85, gene_86, gene_87, gene_88, gene_89, gene_90, gene_91, gene_92, gene_93, gene_94, gene_95, gene_96, gene_97, gene_98, ...]
Index: []

[0 rows x 20534 columns]

In [ ]:
train, test = train_test_split(df, test_size=0.4, random_state=42, shuffle=True)

In [ ]:
#keep in mind that you would need to save this data so that your project is recreateable the same way 
#so now save the train and test files in your repository or drive  ( cause they are randomly sampled)

In [ ]:
os.mkdir('drive/My Drive/Projects/gene_exp_rna_seq/Split1_60_40')
os.listdir("drive/My Drive/Projects/gene_exp_rna_seq")

['data.csv', 'labels.csv', 'labels.gsheet', 'Split1_60_40']

In [ ]:
train_path = os.path.join('drive/My Drive/Projects/gene_exp_rna_seq/Split1_60_40','train.csv')
test_path = os.path.join('drive/My Drive/Projects/gene_exp_rna_seq/Split1_60_40','test.csv')

In [ ]:
train.to_csv(train_path, sep=',', index=False)
test.to_csv(test_path, sep=',', index=False)

In [ ]:
# i Chose test as 40 percent as 20 percent will be for validation and other 20 % for evaluatation 
#so we will split it again .. remember now that when you use the function you use 0.5 cause u need to make half of it 
# the Random State is just same as applying the seed
# if u feel this is video goin slow feel free to increase the speed to 1.5 x

In [ ]:
test , valid = train_test_split(test,test_size=0.5,random_state=42,shuffle=True)

In [ ]:
test_path = os.path.join('drive/My Drive/Projects/gene_exp_rna_seq/Split1_60_40','test.csv')
valid_path = os.path.join('drive/My Drive/Projects/gene_exp_rna_seq/Split1_60_40','valid.csv')

In [ ]:
# we are just rewritnig the test file here

In [ ]:
test.to_csv(train_path, sep=',', index=False)
valid.to_csv(valid_path, sep=',', index=False)

In [ ]:
print("Number of example in Training set " + str(train['Unnamed: 0'].count()));
print("Number of example in Test set "+ str(test['Unnamed: 0'].count()));
print("Number of example in Valid set "+str(test['Unnamed: 0'].count()))

Number of example in Training set 480
Number of example in Test set 160
Number of example in Valid set 160

In [ ]:
#okay so atleast we are 1/4 way now 
#now do you want to split the train data into lavels and features or work as it is ..? 
# tensorflow can work with both together .. but for simplicity sake lets seperate them again into train_labels and train_features 
# do the same for validation data and test data ...

In [ ]:
train_labels = train['Unnamed: 0']
del train['Unnamed: 0']
train_features = train

In [ ]:
test_labels = test['Unnamed: 0']
del test['Unnamed: 0']
test_features = test

valid_labels = valid['Unnamed: 0']
del valid['Unnamed: 0']
valid_features = valid

In [ ]:
#valid_labels;valid_features
#train_labels;train_features

In [ ]:
# so now it is the time to analzise the data ...... See whats there in each row and how are the vlaues ... do they neeed to be normalized . and plot them maybe ... f
#and deduce statstical inference ..

In [ ]:
len(train_features.columns)

20531

In [ ]:
# so thats a lot of features ... basically 20531 features .. omg okay .. not a good idea to plot them 
# i'm thinking for now maybe passs them on directly and seee if model works out ..lol and we do it in other rounf to improve it 
# so as our problem is classification we neeed to one hot encode our labels ..  so we check how many unique values are there in pandas so that many categories
#actually im not used to pandas so i have google the syntax but ts easy
#so we have missed out the main class thing while combining so we might have to just run it again

In [ ]:
train_labels

257    sample_257
766    sample_766
544    sample_544
15      sample_15
3        sample_3
          ...
71      sample_71
106    sample_106
270    sample_270
435    sample_435
102    sample_102
Name: Unnamed: 0, Length: 480, dtype: object