In [131]:
import tensorflow as tf
import numpy as np
import pandas as pd
import os 
import matplotlib.pyplot as plt

In [132]:
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.backend import one_hot

In [133]:
from sklearn.model_selection import train_test_split

In [134]:
os.listdir('drive/My Drive/Projects/gene_exp_rna_seq')

['data.csv', 'labels.csv', 'labels.gsheet', 'Split1_60_40']

In [135]:
data = pd.read_csv('drive/My Drive/Projects/gene_exp_rna_seq/data.csv',delimiter=',')

In [136]:
labels = pd.read_csv('drive/My Drive/Projects/gene_exp_rna_seq/labels.csv',delimiter=',')

In [137]:
data.describe()

           gene_0      gene_1      gene_2  ...  gene_20528  gene_20529  gene_20530
count  801.000000  801.000000  801.000000  ...  801.000000  801.000000  801.000000
mean     0.026642    3.010909    3.095350  ...    9.590726    5.528177    0.095411
std      0.136850    1.200828    1.065601  ...    0.563849    2.073859    0.364529
min      0.000000    0.000000    0.000000  ...    7.864533    0.593975    0.000000
25%      0.000000    2.299039    2.390365  ...    9.244219    4.092385    0.000000
50%      0.000000    3.143687    3.127006  ...    9.566511    5.218618    0.000000
75%      0.000000    3.883484    3.802534  ...    9.917888    6.876382    0.000000
max      1.482332    6.237034    6.063484  ...   12.813320   11.205836    5.254133

[8 rows x 20531 columns]

In [138]:
data.head()

  Unnamed: 0  gene_0    gene_1  ...  gene_20528  gene_20529  gene_20530
0   sample_0     0.0  2.017209  ...    8.921326    5.286759         0.0
1   sample_1     0.0  0.592732  ...    9.397854    2.094168         0.0
2   sample_2     0.0  3.511759  ...   10.090470    1.683023         0.0
3   sample_3     0.0  3.663618  ...    9.684365    3.292001         0.0
4   sample_4     0.0  2.655741  ...    9.461191    5.110372         0.0

[5 rows x 20532 columns]

In [139]:
labels.head()

  Unnamed: 0 Class
0   sample_0  PRAD
1   sample_1  LUAD
2   sample_2  PRAD
3   sample_3  PRAD
4   sample_4  BRCA

In [140]:
data.isnull()

     Unnamed: 0  gene_0  gene_1  ...  gene_20528  gene_20529  gene_20530
0         False   False   False  ...       False       False       False
1         False   False   False  ...       False       False       False
2         False   False   False  ...       False       False       False
3         False   False   False  ...       False       False       False
4         False   False   False  ...       False       False       False
..          ...     ...     ...  ...         ...         ...         ...
796       False   False   False  ...       False       False       False
797       False   False   False  ...       False       False       False
798       False   False   False  ...       False       False       False
799       False   False   False  ...       False       False       False
800       False   False   False  ...       False       False       False

[801 rows x 20532 columns]

In [141]:
data['Unnamed: 0']

0        sample_0
1        sample_1
2        sample_2
3        sample_3
4        sample_4
          ...
796    sample_796
797    sample_797
798    sample_798
799    sample_799
800    sample_800
Name: Unnamed: 0, Length: 801, dtype: object

In [142]:
labels['Unnamed: 0']

0        sample_0
1        sample_1
2        sample_2
3        sample_3
4        sample_4
          ...
796    sample_796
797    sample_797
798    sample_798
799    sample_799
800    sample_800
Name: Unnamed: 0, Length: 801, dtype: object

In [143]:
#split into Train Validation and Test Samples ....... How do you wanna do it ... using a prebuilt function or mannually  ..? your choice .. 
#so lets look up for some function which randomly samples so its easy for everyone 
# We Need to  join both  the labels and the data file cause it would be stupid if we just split the train data seperately from the labels of train data .
# so lets join first and then use the sklearn fucntion of splitting
#so join them on the unnamed column and we need the Class in the dataset that we missed last time (this one)

In [144]:
labels['Class']

0      PRAD
1      LUAD
2      PRAD
3      PRAD
4      BRCA
       ...
796    BRCA
797    LUAD
798    COAD
799    PRAD
800    PRAD
Name: Class, Length: 801, dtype: object

In [145]:
# so we will change the datatype of the labels class to numeric values so we can use one hot encoder or to categorical 
# hope the video lag error in connection dint missed out something

In [146]:
labels = labels.replace({'PRAD': 0})

In [147]:
labels['Class']

0         0
1      LUAD
2         0
3         0
4      BRCA
       ...
796    BRCA
797    LUAD
798    COAD
799       0
800       0
Name: Class, Length: 801, dtype: object

In [148]:
labels['Class'].unique()

array([0, 'LUAD', 'BRCA', 'KIRC', 'COAD'], dtype=object)

In [149]:
#dont forget to start with zero ... hope this method works with to_categorical

In [150]:
labels = labels.replace({'LUAD': 1})
labels = labels.replace({'BRCA': 2})
labels = labels.replace({'KIRC': 3})
labels = labels.replace({'COAD': 4})

In [151]:
labels['Class'].unique()

array([0, 1, 2, 3, 4])

In [152]:
df = pd.DataFrame(data)

In [153]:
#df.join(labels.set_index('Unnamed: 0'), on='Unnamed: 0') # we neewd to change this ................... 
df = pd.merge(df, labels, left_on='Unnamed: 0', right_on='Unnamed: 0', how='left').drop('Unnamed: 0', axis=1)

In [154]:
df

     gene_0    gene_1    gene_2  ...  gene_20529  gene_20530  Class
0       0.0  2.017209  3.265527  ...    5.286759    0.000000      0
1       0.0  0.592732  1.588421  ...    2.094168    0.000000      1
2       0.0  3.511759  4.327199  ...    1.683023    0.000000      0
3       0.0  3.663618  4.507649  ...    3.292001    0.000000      0
4       0.0  2.655741  2.821547  ...    5.110372    0.000000      2
..      ...       ...       ...  ...         ...         ...    ...
796     0.0  1.865642  2.718197  ...    8.819269    0.000000      2
797     0.0  3.942955  4.453807  ...    9.659081    0.000000      1
798     0.0  3.249582  3.707492  ...    4.677458    0.586693      4
799     0.0  2.590339  2.787976  ...    5.718751    0.000000      0
800     0.0  2.325242  3.805932  ...    4.550716    0.000000      0

[801 rows x 20532 columns]

In [155]:
#notice that we have also dropped the labeling of individual samples but it will be fine since we have unique samples and we have the entries from 0 to 800 respectively of each samples

In [156]:
train, test = train_test_split(df, test_size=0.4, random_state=42, shuffle=True)

In [157]:
#keep in mind that you would need to save this data so that your project is recreateable the same way 
#so now save the train and test files in your repository or drive  ( cause they are randomly sampled)

In [158]:
#os.mkdir('drive/My Drive/Projects/gene_exp_rna_seq/Split1_60_40')
os.listdir("drive/My Drive/Projects/gene_exp_rna_seq")

['data.csv', 'labels.csv', 'labels.gsheet', 'Split1_60_40']

In [159]:
train_path = os.path.join('drive/My Drive/Projects/gene_exp_rna_seq/Split1_60_40','train.csv')
test_path = os.path.join('drive/My Drive/Projects/gene_exp_rna_seq/Split1_60_40','test.csv')

In [160]:
train.to_csv(train_path, sep=',', index=False)
test.to_csv(test_path, sep=',', index=False)

In [161]:
# i Chose test as 40 percent as 20 percent will be for validation and other 20 % for evaluatation 
#so we will split it again .. remember now that when you use the function you use 0.5 cause u need to make half of it 
# the Random State is just same as applying the seed
# if u feel this is video goin slow feel free to increase the speed to 1.5 x

In [162]:
test , valid = train_test_split(test,test_size=0.5,random_state=42,shuffle=True)

In [163]:
test_path = os.path.join('drive/My Drive/Projects/gene_exp_rna_seq/Split1_60_40','test.csv')
valid_path = os.path.join('drive/My Drive/Projects/gene_exp_rna_seq/Split1_60_40','valid.csv')

In [164]:
# we are just rewritnig the test file here

In [165]:
test.to_csv(train_path, sep=',', index=False)
valid.to_csv(valid_path, sep=',', index=False)

In [166]:
#we would have to change the below code since we dropped that column column # so i forgot to save day 0 notebook in git gub  but will save from day 1

In [167]:
print("Number of example in Training set " + str(train['Class'].count()));
print("Number of example in Test set "+ str(test['Class'].count()));
print("Number of example in Valid set "+str(test['Class'].count()))

Number of example in Training set 480
Number of example in Test set 160
Number of example in Valid set 160

In [168]:
#okay so atleast we are 1/4 way now 
#now do you want to split the train data into lavels and features or work as it is ..? 
# tensorflow can work with both together .. but for simplicity sake lets seperate them again into train_labels and train_features 
# do the same for validation data and test data ... 
# so recorrecting the mistakes we made yesterday .. sorry for that

In [169]:
train_labels = train['Class']
del train['Class']
train_features = train

In [170]:
test_labels = test['Class']
del test['Class']
test_features = test

valid_labels = valid['Class']
del valid['Class']
valid_features = valid

In [171]:
valid_labels#;valid_features
#train_labels;train_features

381    3
81     0
181    3
456    1
76     2
      ..
711    3
737    2
467    2
703    3
518    1
Name: Class, Length: 161, dtype: int64

In [172]:
# so now it is the time to analzise the data ...... See whats there in each row and how are the vlaues ... do they neeed to be normalized . and plot them maybe ... f
#and deduce statstical inference ..

In [173]:
len(train_features.columns)

20531

In [174]:
# so thats a lot of features ... basically 20531 features .. omg okay .. not a good idea to plot them 
# i'm thinking for now maybe passs them on directly and seee if model works out ..lol and we do it in other rounf to improve it 
# so as our problem is classification we neeed to one hot encode our labels ..  so we check how many unique values are there in pandas so that many categories
#actually im not used to pandas so i have google the syntax but ts easy
#so we have missed out the main class thing while combining so we might have to just run it again --- So we merge it propely today 20-10-2020

In [175]:
train_labels

257    0
766    4
544    2
15     2
3      0
      ..
71     2
106    1
270    3
435    3
102    2
Name: Class, Length: 480, dtype: int64

In [176]:
# lets see how many classes we have and conform that

In [177]:
labels['Class'].unique()

array([0, 1, 2, 3, 4])

In [178]:
# so we have 5 classes in total , that mean are final output layers myst have 5 neurons 
#now its time to make them categorical data so we use the util from keras
#but first we might need to convert it into nummpy array from pandas

In [179]:
train_labels = pd.DataFrame(train_labels).to_numpy()

In [180]:
train_labels.shape

(480, 1)

In [181]:
# we may need to do it for all out trin and test set so lets do 
# also remebemr that dont run that cell twice cause it will add and additional dimension somethime (np.array(array) this one)

In [182]:
test_labels = pd.DataFrame(test_labels).to_numpy()
valid_labels = pd.DataFrame(valid_labels).to_numpy()
train_features = pd.DataFrame(train_features).to_numpy()
test_features = pd.DataFrame(test_features).to_numpy()
valid_features = pd.DataFrame(valid_features).to_numpy()

In [183]:
# no to categorical for labels .. try with one first 
# so to_categorical need numeric value .. lets try with one hot encod or else we convert them to numeric values ourself 
# so we might have to convert all this into numeric values  and i have never done it before so its gonna be lot of googleuing about the pandas syntax
# we might just do it at the begining of the notebook so its easy

In [184]:
train_labels_categorical = to_categorical(train_labels,5)
train_labels_one_hot = tf.keras.backend.one_hot(train_labels, 5)

In [188]:
train_labels_categorical.shape

(480, 5)

In [210]:
valid_labels_categorical = to_categorical(valid_labels,5)
test_labels_categorical = to_categorical(test_labels,5)

In [189]:
# so both of them works the same way ,, but one_hot method give a tensorflow array type while to_categorical givews a numpy array

In [201]:
train_features[0]

array([ 0.        ,  4.39652943,  4.15279185, ..., 10.21771541,
        4.3483245 ,  0.30591217])

In [208]:
# so our our one single input has 20531 fetaures 
# now should we normalize the data ..? or keep it as it is ..?
# normalizing might be better since the model would then get a better idea about the relation 
# so lets try normalizing with tensorflow numpy array 
# we will normalize along the vertical axis that is for each gene # i often get confuse with axis = 0 and 1 so lets try and see
# the first running vertically downwards across rows (axis 0), and the second running horizontally across columns (axis 1).
# So we follow this

In [204]:
train_features

array([[ 0.        ,  4.39652943,  4.15279185, ..., 10.21771541,
         4.3483245 ,  0.30591217],
       [ 0.        ,  3.35133151,  3.51227746, ...,  9.57867082,
         4.95142927,  0.        ],
       [ 0.        ,  2.6513158 ,  2.25794595, ..., 10.39690442,
         5.96270633,  0.        ],
       ...,
       [ 0.        ,  2.52839628,  2.62030488, ...,  9.27967093,
         4.18972969,  0.        ],
       [ 0.        ,  4.13419629,  3.7226081 , ..., 10.02350487,
         6.3917093 ,  0.        ],
       [ 0.        ,  2.99048296,  2.48735772, ..., 10.17624796,
         6.94138806,  0.        ]])

In [206]:
train_feature_norm = tf.keras.utils.normalize(train_features, axis=0, order=2)

In [209]:
train_feature_norm.shape

(480, 20531)

In [212]:
test_feature_norm = tf.keras.utils.normalize(test_features, axis=0, order=2)
valid_feature_norm = tf.keras.utils.normalize(valid_features, axis=0, order=2)

In [211]:
# so yooyyo here we have finished half of our project .. categorized  and normalized .. now just model building  
# we could have done this before splitting the data set also but we dint see that comming ,,, i guess its better to do this there but we would have to 
#look up for normalize function in pandas while its easy in keras api so .... either way things are easy